try fix errors

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -18,20 +18,27 @@ jobs:
         shell: bash
         working-directory: ./terraform
     steps:
-      - name: "Checkout source code"
-        uses: actions/checkout@v5
+      - name: Validate confirmation
+        run: |
+          if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
+            echo "Error: You must type 'destroy' to confirm resource deletion"
+            exit 1
+          fi
+    
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: "Setup Terraform on the runner"
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.6.3 # same as in `terraform.tf`
 
-      - name: Configure AWS credentials
+      - name: "Configure AWS credentials"
         uses: aws-actions/configure-aws-credentials@v1
         with:
-            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            aws-region: ${{ env.AWS_REGION }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: "Terraform init"
         id: tf-init
